import {
  Business,
  Treasury,
  Vendor,
  Contract,
  Invoice,
  Payment,
  Policy,
  Approval,
  UpcomingObligation,
  AuditEvent,
  ActivityFeedItem,
} from '@/types';

export function getInitialSeedData() {
  const business: Business = {
    id: 'biz_africode',
    name: 'AfriCode Labs',
    createdAt: '2026-01-15T09:00:00Z',
  };

  const treasury: Treasury = {
    id: 'tr_001',
    businessId: 'biz_africode',
    balance: 12400,
    reserved: 5850,
    operatingReserve: 5000,
    available: 6550, // 12400 - 5850 = 6550 discretionary
    currency: 'USDC',
    walletAddress: '0x4a92E31Fb2C7D167a58a74e5F31b99b5aC04b7c1',
    network: 'Arc',
    updatedAt: new Date().toISOString(),
  };

  const policy: Policy = {
    id: 'pol_default',
    businessId: 'biz_africode',
    autonomousLimit: 1000,
    dailyLimit: 5000,
    dailySpent: 750,
    minimumReserve: 5000,
    newVendorRequiresApproval: true,
    milestoneRequired: true,
    duplicateProtection: true,
    flaggedCounterpartyProtection: true,
    payrollPriority: 'HIGH',
    criticalInfraPriority: 'HIGH',
    discretionaryPriority: 'NORMAL',
    isAutonomousPaused: false,
    updatedAt: new Date().toISOString(),
  };

  const vendors: Vendor[] = [
    {
      id: 'ven_abc',
      businessId: 'biz_africode',
      name: 'ABC Design',
      category: 'Contractor',
      walletAddress: '0x8f4d92a15c8e31002ba5032a91f42d992a91e4f2',
      approved: true,
      riskStatus: 'NORMAL',
      createdAt: '2026-02-01T10:00:00Z',
      contractsCount: 1,
      totalPaid: 7250,
    },
    {
      id: 'ven_aws',
      businessId: 'biz_africode',
      name: 'AWS',
      category: 'Cloud',
      walletAddress: '0x3d7b4a22c09191e4f358a9809cb8d95180aa4e3',
      approved: true,
      riskStatus: 'NORMAL',
      createdAt: '2026-01-20T10:00:00Z',
      contractsCount: 1,
      totalPaid: 3600,
    },
    {
      id: 'ven_vercel',
      businessId: 'biz_africode',
      name: 'Vercel',
      category: 'SaaS',
      walletAddress: '0x91ef38a0928cdb2210a48d88e0172cc771bca42',
      approved: true,
      riskStatus: 'NORMAL',
      createdAt: '2026-01-22T10:00:00Z',
      contractsCount: 1,
      totalPaid: 900,
    },
    {
      id: 'ven_openai',
      businessId: 'biz_africode',
      name: 'OpenAI',
      category: 'AI',
      walletAddress: '0x5a183d29199bcf2018ea37a4e09dc08819bc231',
      approved: true,
      riskStatus: 'NORMAL',
      createdAt: '2026-02-10T10:00:00Z',
      contractsCount: 1,
      totalPaid: 1140,
    },
    {
      id: 'ven_unknown',
      businessId: 'biz_africode',
      name: 'Unknown Vendor',
      category: 'Unknown',
      walletAddress: '0x77ab4210cf941a80d456120199e4f51bc728a3',
      approved: false,
      riskStatus: 'PENDING_VERIFICATION',
      createdAt: '2026-09-24T14:30:00Z',
      contractsCount: 0,
      totalPaid: 0,
    },
  ];

  const contracts: Contract[] = [
    {
      id: 'ct_024',
      vendorId: 'ven_abc',
      reference: 'CT-024',
      title: 'Mobile & Web UI/UX Redesign System',
      totalAmount: 12000,
      currency: 'USDC',
      status: 'ACTIVE',
      milestones: [
        {
          id: 'ms_1',
          number: 1,
          title: 'Design System Architecture & Typography',
          amount: 2000,
          completed: true,
          verifiedAt: '2026-06-15T12:00:00Z',
        },
        {
          id: 'ms_2',
          number: 2,
          title: 'Core Dashboard & Web Flow Specs',
          amount: 2000,
          completed: true,
          verifiedAt: '2026-07-20T12:00:00Z',
        },
        {
          id: 'ms_3',
          number: 3,
          title: 'Component Library & Tailwind Tokens',
          amount: 2500,
          completed: true,
          verifiedAt: '2026-08-18T12:00:00Z',
        },
        {
          id: 'ms_4',
          number: 4,
          title: 'Mobile Responsive Audit & Asset Export',
          amount: 750,
          completed: true,
          verifiedAt: '2026-09-24T09:15:00Z',
        },
        {
          id: 'ms_5',
          number: 5,
          title: 'Full Design QA, Native Design System & Handover',
          amount: 4800,
          completed: true,
          verifiedAt: '2026-09-25T14:00:00Z',
        },
      ],
    },
    {
      id: 'ct_aws',
      vendorId: 'ven_aws',
      reference: 'CT-AWS-2026',
      title: 'Enterprise Cloud Infrastructure Services',
      totalAmount: 10800,
      currency: 'USDC',
      status: 'ACTIVE',
      milestones: [
        {
          id: 'ms_aws_sep',
          number: 9,
          title: 'September Multi-AZ Cloud Hosting & Compute',
          amount: 900,
          completed: true,
          verifiedAt: '2026-09-25T11:00:00Z',
        },
      ],
    },
  ];

  const invoices: Invoice[] = [
    {
      id: 'inv_1042',
      vendorId: 'ven_abc',
      vendorName: 'ABC Design',
      contractId: 'ct_024',
      contractRef: 'CT-024',
      milestoneId: 'ms_4',
      milestoneNumber: 4,
      number: 'INV-1042',
      amount: 750,
      currency: 'USDC',
      issueDate: '2026-09-24',
      dueDate: '2026-09-24',
      status: 'AUTONOMOUS_PAID',
      verificationStatus: 'VERIFIED',
      aiDecision: 'ALLOW',
      aiExplanation:
        'ABC Design is an approved vendor. Invoice INV-1042 matches contract CT-024 and milestone 4 has been verified. The $750 payment is below the $1,000 autonomous-payment limit, and the company\'s minimum treasury reserve remains protected.',
      isDuplicate: false,
      lineItems: [
        {
          description: 'Milestone 4: Mobile Responsive Audit & Asset Export',
          quantity: 1,
          unitPrice: 750,
          total: 750,
        },
      ],
      paymentId: 'pay_1042',
      transactionHash: '0x8f4d92a1e7b24901cb9159048a20918c5e317042a91',
      checksSnapshot: [
        { key: 'vendor_verified', label: 'Vendor verified', passed: true, details: 'Identity verified against business register' },
        { key: 'vendor_approved', label: 'Approved vendor', passed: true, details: 'ABC Design is on the active whitelist' },
        { key: 'contract_exists', label: 'Contract exists', passed: true, details: 'Linked to active contract CT-024' },
        { key: 'contract_matches', label: 'Contract amount matches', passed: true, details: 'Invoice amount $750 matches milestone specification' },
        { key: 'milestone_completed', label: 'Milestone completed', passed: true, details: 'Milestone 4 verified by technical lead' },
        { key: 'not_duplicate', label: 'Invoice not duplicated', passed: true, details: 'No prior submission for INV-1042' },
        { key: 'treasury_sufficient', label: 'Treasury sufficient', passed: true, details: 'Available balance $6,550 exceeds $750' },
        { key: 'reserve_maintained', label: 'Minimum reserve maintained', passed: true, details: 'Post-payment operating balance remains above $5,000 reserve' },
        { key: 'below_autonomous_limit', label: 'Payment below autonomous limit', passed: true, details: '$750 is within $1,000 autonomous threshold' },
      ],
      createdAt: '2026-09-24T09:40:00Z',
    },
    {
      id: 'inv_1043',
      vendorId: 'ven_abc',
      vendorName: 'ABC Design',
      contractId: 'ct_024',
      contractRef: 'CT-024',
      milestoneId: 'ms_4',
      milestoneNumber: 4,
      number: 'INV-1043-DUP',
      amount: 750,
      currency: 'USDC',
      issueDate: '2026-09-25',
      dueDate: '2026-09-25',
      status: 'BLOCKED',
      verificationStatus: 'FAILED',
      aiDecision: 'BLOCK',
      aiExplanation:
        'Payment blocked because this invoice appears to have already been processed (duplicate claim for Milestone 4 already fulfilled by INV-1042).',
      isDuplicate: true,
      lineItems: [
        {
          description: 'Milestone 4: Duplicate Submission for Mobile Responsive Flows',
          quantity: 1,
          unitPrice: 750,
          total: 750,
        },
      ],
      checksSnapshot: [
        { key: 'vendor_verified', label: 'Vendor verified', passed: true, details: 'Vendor recognized' },
        { key: 'vendor_approved', label: 'Approved vendor', passed: true, details: 'ABC Design is approved' },
        { key: 'contract_exists', label: 'Contract exists', passed: true, details: 'Contract CT-024 found' },
        { key: 'milestone_completed', label: 'Milestone completed', passed: false, details: 'Milestone 4 was already paid under INV-1042' },
        { key: 'not_duplicate', label: 'Invoice not duplicated', passed: false, details: 'Duplicate hash detected: duplicate of INV-1042', isCritical: true },
        { key: 'policy_block', label: 'Mandate duplicate rule', passed: false, details: 'Mandate policy strictly blocks duplicate claims' },
      ],
      createdAt: '2026-09-25T11:20:00Z',
    },
    {
      id: 'inv_1044',
      vendorId: 'ven_abc',
      vendorName: 'ABC Design',
      contractId: 'ct_024',
      contractRef: 'CT-024',
      milestoneId: 'ms_5',
      milestoneNumber: 5,
      number: 'INV-1044',
      amount: 4800,
      currency: 'USDC',
      issueDate: '2026-09-26',
      dueDate: '2026-09-28',
      status: 'APPROVAL_REQUIRED',
      verificationStatus: 'VERIFIED',
      aiDecision: 'APPROVAL_REQUIRED',
      aiExplanation:
        'The invoice is fully verified, but exceeds OLOWO\'s autonomous authority ($4,800 > $1,000 autonomous limit). Human approval is required before settlement.',
      isDuplicate: false,
      lineItems: [
        {
          description: 'Milestone 5: Full Design QA, Native Design System & Handover',
          quantity: 1,
          unitPrice: 4800,
          total: 4800,
        },
      ],
      checksSnapshot: [
        { key: 'vendor_verified', label: 'Vendor verified', passed: true, details: 'ABC Design verified' },
        { key: 'vendor_approved', label: 'Approved vendor', passed: true, details: 'Active whitelist vendor' },
        { key: 'contract_exists', label: 'Contract exists', passed: true, details: 'Linked to CT-024' },
        { key: 'contract_matches', label: 'Contract amount matches', passed: true, details: 'Matches Milestone 5 contract value ($4,800)' },
        { key: 'milestone_completed', label: 'Milestone completed', passed: true, details: 'Milestone 5 marked complete & verified' },
        { key: 'not_duplicate', label: 'Invoice not duplicated', passed: true, details: 'Unique invoice record' },
        { key: 'treasury_sufficient', label: 'Treasury sufficient', passed: true, details: 'Current operating balance ($12,400) covers amount' },
        { key: 'reserve_maintained', label: 'Minimum reserve maintained', passed: true, details: '$12,400 - $4,800 = $7,600, which exceeds $5,000 reserve' },
        { key: 'below_autonomous_limit', label: 'Payment below autonomous limit', passed: false, details: '$4,800 exceeds $1,000 autonomous threshold', isCritical: true },
      ],
      createdAt: '2026-09-26T08:15:00Z',
    },
    {
      id: 'inv_1045',
      vendorId: 'ven_unknown',
      vendorName: 'Unknown Vendor',
      number: 'INV-1045',
      amount: 500,
      currency: 'USDC',
      issueDate: '2026-09-25',
      dueDate: '2026-09-30',
      status: 'APPROVAL_REQUIRED',
      verificationStatus: 'FAILED',
      aiDecision: 'APPROVAL_REQUIRED',
      aiExplanation:
        'Payment requires approval because the recipient is not an approved vendor in the company directory.',
      isDuplicate: false,
      lineItems: [
        {
          description: 'Ad-hoc Digital Infrastructure Consulting',
          quantity: 1,
          unitPrice: 500,
          total: 500,
        },
      ],
      checksSnapshot: [
        { key: 'vendor_verified', label: 'Vendor verified', passed: true, details: 'Counterparty identified' },
        { key: 'vendor_approved', label: 'Approved vendor', passed: false, details: 'Vendor is not in approved directory', isCritical: true },
        { key: 'contract_exists', label: 'Contract exists', passed: false, details: 'No active contract on file' },
        { key: 'treasury_sufficient', label: 'Treasury sufficient', passed: true, details: 'Funds available' },
        { key: 'reserve_maintained', label: 'Minimum reserve maintained', passed: true, details: 'Reserve protected' },
        { key: 'below_autonomous_limit', label: 'Payment below autonomous limit', passed: true, details: '$500 is within $1,000 limit' },
      ],
      createdAt: '2026-09-25T14:45:00Z',
    },
    {
      id: 'inv_1046',
      vendorId: 'ven_aws',
      vendorName: 'AWS',
      contractId: 'ct_aws',
      contractRef: 'CT-AWS-2026',
      number: 'INV-AWS-8821',
      amount: 900,
      currency: 'USDC',
      issueDate: '2026-09-26',
      dueDate: '2026-10-01',
      status: 'VERIFIED',
      verificationStatus: 'VERIFIED',
      aiDecision: 'ALLOW',
      aiExplanation:
        'Verified critical infrastructure bill. Reserved $900 from available funds to guarantee timely payment upon due date.',
      isDuplicate: false,
      lineItems: [
        {
          description: 'AWS September Cloud Hosting & RDS Database Cluster',
          quantity: 1,
          unitPrice: 900,
          total: 900,
        },
      ],
      checksSnapshot: [
        { key: 'vendor_verified', label: 'Vendor verified', passed: true, details: 'Amazon Web Services verified' },
        { key: 'vendor_approved', label: 'Approved vendor', passed: true, details: 'AWS is an authorized critical infrastructure vendor' },
        { key: 'below_autonomous_limit', label: 'Payment below autonomous limit', passed: true, details: '$900 is within $1,000 limit' },
        { key: 'reserve_maintained', label: 'Minimum reserve maintained', passed: true, details: 'Operating reserve protected' },
      ],
      createdAt: '2026-09-26T06:00:00Z',
    },
    {
      id: 'inv_1047',
      vendorId: 'ven_vercel',
      vendorName: 'Vercel',
      number: 'INV-VERC-9102',
      amount: 450,
      currency: 'USDC',
      issueDate: '2026-09-26',
      dueDate: '2026-10-05',
      status: 'VERIFIED',
      verificationStatus: 'VERIFIED',
      aiDecision: 'ALLOW',
      aiExplanation:
        'Verified recurring deployment and edge compute subscription. Scheduled for settlement on due date.',
      isDuplicate: false,
      lineItems: [
        {
          description: 'Vercel Enterprise Edge Hosting & Analytics',
          quantity: 1,
          unitPrice: 450,
          total: 450,
        },
      ],
      checksSnapshot: [
        { key: 'vendor_verified', label: 'Vendor verified', passed: true, details: 'Vercel Inc. verified' },
        { key: 'vendor_approved', label: 'Approved vendor', passed: true, details: 'Approved vendor' },
        { key: 'below_autonomous_limit', label: 'Payment below autonomous limit', passed: true, details: '$450 is within $1,000 limit' },
      ],
      createdAt: '2026-09-26T07:30:00Z',
    },
  ];

  const payments: Payment[] = [
    {
      id: 'pay_1042',
      invoiceId: 'inv_1042',
      invoiceNumber: 'INV-1042',
      vendorId: 'ven_abc',
      vendorName: 'ABC Design',
      amount: 750,
      currency: 'USDC',
      status: 'COMPLETED',
      authorizationType: 'AUTONOMOUS',
      network: 'Arc',
      circleWalletId: 'w_circ_africode_treasury_01',
      transactionHash: '0x8f4d92a1e7b24901cb9159048a20918c5e317042a91',
      createdAt: '2026-09-24T09:42:15Z',
      policyChecksSnapshot: invoices[0].checksSnapshot,
    },
    {
      id: 'pay_1048',
      invoiceId: 'inv_1048',
      invoiceNumber: 'INV-OAI-3301',
      vendorId: 'ven_openai',
      vendorName: 'OpenAI',
      amount: 380,
      currency: 'USDC',
      status: 'COMPLETED',
      authorizationType: 'AUTONOMOUS',
      network: 'Arc',
      circleWalletId: 'w_circ_africode_treasury_01',
      transactionHash: '0x3c990a184ef29810bb73194a081734bc7e829101ff',
      createdAt: '2026-09-24T04:10:00Z',
      policyChecksSnapshot: [
        { key: 'vendor_approved', label: 'Approved vendor', passed: true, details: 'OpenAI is whitelisted' },
        { key: 'below_autonomous_limit', label: 'Payment below autonomous limit', passed: true, details: '$380 is within $1,000 limit' },
        { key: 'reserve_maintained', label: 'Minimum reserve maintained', passed: true, details: 'Reserve maintained' },
      ],
    },
  ];

  const approvals: Approval[] = [
    {
      id: 'appr_1044',
      invoiceId: 'inv_1044',
      invoiceNumber: 'INV-1044',
      vendorName: 'ABC Design',
      vendorId: 'ven_abc',
      amount: 4800,
      currency: 'USDC',
      status: 'PENDING',
      reason: 'The invoice is fully verified, but exceeds OLOWO\'s autonomous authority ($1,000 limit).',
      aiRecommendation: 'APPROVE',
      checksSummary: [
        'Vendor verified',
        'Contract CT-024 verified',
        'Milestone 5 completed',
        'Treasury sufficient',
      ],
      requestedAt: '2026-09-26T08:15:30Z',
    },
    {
      id: 'appr_1045',
      invoiceId: 'inv_1045',
      invoiceNumber: 'INV-1045',
      vendorName: 'Unknown Vendor',
      vendorId: 'ven_unknown',
      amount: 500,
      currency: 'USDC',
      status: 'PENDING',
      reason: 'Recipient is not an approved vendor in the company directory.',
      aiRecommendation: 'APPROVE',
      checksSummary: [
        'Counterparty identified',
        'Within spending limit ($500 < $1,000)',
        'Requires vendor whitelist confirmation',
      ],
      requestedAt: '2026-09-25T14:45:00Z',
    },
  ];

  const upcomingObligations: UpcomingObligation[] = [
    {
      id: 'ob_1',
      title: 'AWS Infrastructure Services',
      vendorName: 'AWS',
      vendorId: 'ven_aws',
      amount: 900,
      currency: 'USDC',
      dueDate: '2026-10-01',
      daysUntilDue: 5,
      isReserved: true,
      priority: 'CRITICAL',
    },
    {
      id: 'ob_2',
      title: 'Contractor Milestone Retainer',
      vendorName: 'ABC Design',
      vendorId: 'ven_abc',
      amount: 750,
      currency: 'USDC',
      dueDate: '2026-09-28',
      daysUntilDue: 2,
      isReserved: true,
      priority: 'HIGH',
    },
    {
      id: 'ob_3',
      title: 'Vercel Enterprise Edge Hosting',
      vendorName: 'Vercel',
      vendorId: 'ven_vercel',
      amount: 450,
      currency: 'USDC',
      dueDate: '2026-10-05',
      daysUntilDue: 9,
      isReserved: false,
      priority: 'HIGH',
    },
    {
      id: 'ob_4',
      title: 'OpenAI API Compute Tier',
      vendorName: 'OpenAI',
      vendorId: 'ven_openai',
      amount: 400,
      currency: 'USDC',
      dueDate: '2026-10-10',
      daysUntilDue: 14,
      isReserved: false,
      priority: 'HIGH',
    },
    {
      id: 'ob_5',
      title: 'Contractor Design QA Final Milestone',
      vendorName: 'ABC Design',
      vendorId: 'ven_abc',
      amount: 4800,
      currency: 'USDC',
      dueDate: '2026-09-28',
      daysUntilDue: 2,
      isReserved: false,
      priority: 'NORMAL',
    },
  ];

  const auditEvents: AuditEvent[] = [
    {
      id: 'aud_1',
      businessId: 'biz_africode',
      timestamp: '2026-09-24T09:42:15Z',
      action: 'PAYMENT_EXECUTED',
      entity: 'ABC Design',
      entityType: 'PAYMENT',
      entityId: 'pay_1042',
      amount: 750,
      decision: 'ALLOWED',
      reason:
        'Contract milestone 4 verified. Vendor approved. No duplicate invoice detected. Treasury reserve maintained. Payment within autonomous limit.',
      policyChecks: invoices[0].checksSnapshot,
      authorization: 'AUTONOMOUS',
      transactionHash: '0x8f4d92a1e7b24901cb9159048a20918c5e317042a91',
      circleRef: 'circ_tx_88201a9',
    },
    {
      id: 'aud_2',
      businessId: 'biz_africode',
      timestamp: '2026-09-25T11:20:00Z',
      action: 'PAYMENT_BLOCKED',
      entity: 'ABC Design',
      entityType: 'INVOICE',
      entityId: 'inv_1043',
      amount: 750,
      decision: 'BLOCKED',
      reason: 'Duplicate invoice detected for Milestone 4 already settled under INV-1042.',
      policyChecks: invoices[1].checksSnapshot,
      authorization: 'SYSTEM',
    },
    {
      id: 'aud_3',
      businessId: 'biz_africode',
      timestamp: '2026-09-26T06:05:00Z',
      action: 'OBLIGATION_RESERVED',
      entity: 'AWS',
      entityType: 'TREASURY',
      entityId: 'inv_1046',
      amount: 900,
      decision: 'RESERVED',
      reason: 'Reserved $900 for upcoming AWS infrastructure obligation due in 5 days.',
      policyChecks: invoices[4].checksSnapshot,
      authorization: 'AUTONOMOUS',
    },
    {
      id: 'aud_4',
      businessId: 'biz_africode',
      timestamp: '2026-09-26T08:15:30Z',
      action: 'APPROVAL_REQUESTED',
      entity: 'ABC Design',
      entityType: 'INVOICE',
      entityId: 'inv_1044',
      amount: 4800,
      decision: 'APPROVAL_REQUIRED',
      reason:
        'Invoice INV-1044 ($4,800) is fully verified but exceeds the $1,000 autonomous spending limit. Routed to business owner for sign-off.',
      policyChecks: invoices[2].checksSnapshot,
      authorization: 'SYSTEM',
    },
    {
      id: 'aud_5',
      businessId: 'biz_africode',
      timestamp: '2026-09-25T14:45:00Z',
      action: 'APPROVAL_REQUESTED',
      entity: 'Unknown Vendor',
      entityType: 'VENDOR',
      entityId: 'inv_1045',
      amount: 500,
      decision: 'APPROVAL_REQUIRED',
      reason: 'Recipient Skyline Global Media is not an approved vendor in the company directory.',
      policyChecks: invoices[3].checksSnapshot,
      authorization: 'SYSTEM',
    },
  ];

  const activityFeed: ActivityFeedItem[] = [
    {
      id: 'act_1',
      type: 'VERIFICATION',
      iconType: 'check',
      title: 'Verified ABC Design invoice',
      subtitle: 'INV-1044 verified against contract CT-024 (Milestone 5)',
      amount: 4800,
      timestamp: '2026-09-26T08:15:00Z',
      timeAgo: 'Just now',
      linkUrl: '/invoices/inv_1044',
    },
    {
      id: 'act_2',
      type: 'APPROVAL_REQUEST',
      iconType: 'alert',
      title: 'Approval requested',
      subtitle: 'ABC Design invoice exceeds $1,000 autonomous mandate',
      amount: 4800,
      timestamp: '2026-09-26T08:15:30Z',
      timeAgo: '12 min ago',
      linkUrl: '/approvals',
    },
    {
      id: 'act_3',
      type: 'RESERVE',
      iconType: 'reserve',
      title: 'Reserved AWS obligation',
      subtitle: 'Protected $900 for critical infrastructure due in 5 days',
      amount: 900,
      timestamp: '2026-09-26T06:05:00Z',
      timeAgo: '2 hours ago',
      linkUrl: '/treasury',
    },
    {
      id: 'act_4',
      type: 'PAYMENT',
      iconType: 'payment',
      title: 'Paid ABC Design',
      subtitle: 'Milestone 4 settled autonomously via Arc USDC',
      amount: 750,
      timestamp: '2026-09-24T09:42:15Z',
      timeAgo: '2 days ago',
      linkUrl: '/payments',
    },
    {
      id: 'act_5',
      type: 'BLOCK',
      iconType: 'block',
      title: 'Blocked duplicate claim',
      subtitle: 'Rejected duplicate claim for Milestone 4 (INV-1043)',
      amount: 750,
      timestamp: '2026-09-25T11:20:00Z',
      timeAgo: 'Yesterday',
      linkUrl: '/decisions',
    },
  ];

  return {
    business,
    treasury,
    policy,
    vendors,
    contracts,
    invoices,
    payments,
    approvals,
    upcomingObligations,
    auditEvents,
    activityFeed,
  };
}
